# Generated by Django 2.2.5 on 2021-05-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210508_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
