# Generated by Django 2.2.5 on 2021-05-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CovidHelp', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='conetnt',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='post',
        ),
    ]
