# Generated by Django 2.2.5 on 2021-05-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CovidHelp', '0003_auto_20210508_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='CovidHelp.Post'),
        ),
    ]
