# Generated by Django 2.2.5 on 2021-05-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidHelp', '0004_auto_20210508_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='help_type',
            field=models.CharField(choices=[('1', 'Plasma'), ('2', 'Oxygen'), ('3', 'Bed'), ('4', 'Emergency')], max_length=300, null=True),
        ),
    ]
